### ISSUE TITLE
weird hanging

### ISSUE THREAD

**Issue by xuanzon** [addaleax/lzma-native#10]
node.js: v4.1.1
 lzma-native: 0.3.9
i try:
var fs = require('fs');
var lzma = require('lzma-native');
var r = fs.createReadStream('test.jpg');
var compressor = lzma.createCompressor();
var decompressor = lzma.createDecompressor();
var w = fs.createWriteStream('test2.jpg');
r.pipe(compressor).pipe(decompressor).pipe(w);

test2.jpg is generated correctly, but execution wont stop.

**Comment by addaleax** [comment]
Okay, I can confirm this – will probably fix it within the next hours :)

**Comment by addaleax** [comment]
I’ll just wait for the tests to pass and then I’ll publish this as 0.3.10

**Comment by addaleax** [comment]
Done, fix published as 0.3.10. I don’t think this should be considered a huge bug anyway, since the hang would have stopped with the next garbage collection (which would happen somewhat regularly in larger applications).

I hope this module will be useful to you – Let me know if there happen to be any more problems!

**Comment by xuanzon** [comment]
yes, it works now.
thank you for your effort :)
