### ISSUE TITLE
lzma-native > node-pre-gyp@0.11.0: Please upgrade to @mapbox/node-pre-gyp: the non-scoped node-pre-gyp package is deprecated and only the @mapbox scoped package will recieve updates in the future`

### ISSUE THREAD

**Issue by raphael10-collab** [addaleax/lzma-native#103]
Installing electron-rebuild : 
`warning electron-rebuild > lzma-native > node-pre-gyp@0.11.0: Please upgrade to @mapbox/node-pre-gyp: the non-scoped node-pre-gyp package is deprecated and only the @mapbox scoped package will recieve updates in the future`

- O.S. : Ubuntu 18.04 Desktop
- node: v14.5.0

**Comment by addaleax** [comment]
Then feel free to send a PR

**Comment by raphael10-collab** [comment]
@addaleax Yesterday, which was Sunday, I wrote SIX of those upgrading requests. And received for most of them a "send a PR" as response.
If the library's maintainer thinks it's a low priority to upgrade/maintain her/his library's packages, why its users should send a PR?
Shouldn't be the duty and responsability of the library's maintainers to keep library' packages upgraded/maintained?
It's like my children's room: it' true, we live in the same house, but it's their duty and responsability to keep their room tidy.
If everyone does his/her duty, the house keeps going safe and tidy.

Anyway, if you still think I, as final user of YOUR library, has to make the PR for upgrading the packages your library relies on, whenever I will have spare time, I will do it

**Comment by dopry** [comment]
@raphael10-collab @addaleax is providing this code free for your use and has absolutely zero responsibility to maintain it for you.  There is no excuse for taking your frustration out on @addaleax. If you don't want to write a PR, just say, "Thanks for all your work! I don't think I have time to make a PR. Hopefully, someone else does."  Or maybe take some time to write the PR and give back rather than complaining to people who have already given you something out of the kindness of their heart.

**Comment by addaleax** [comment]
lzma-native@8.x is identical to @7.x except that it uses prebuildify instead of node-pre-gyp, so a lot of these issues should have gone away now. Please let me know if anything doesn’t work as it should!
