### ISSUE TITLE
Decompressor stream hangs

### ISSUE THREAD

**Issue by atombender** [addaleax/lzma-native#11]
The decompressor hangs on my files, compressed with xz from liblzma 5.1.0alpha (on Ubuntu Trusty). For my files it looks like it pretty consistently happens around > 650MB.

[Here](https://www.dropbox.com/s/wqbwa2f9f9ylstc/test.xz?dl=0) is a test file.

My test script (ES6):

```js
'use strict';

import lzma from 'lzma-native';
import fs from 'fs';
import split from 'split';
import stream from 'stream';

let byteCount = 0;

class TestWriter extends stream.Writable {
  constructor() {
    super({objectMode: true});
    this.count = 0;
  }

  _write(obj, encoding, callback) {
    if ((this.count++ % 10000) === 0) {
      console.log(`${this.count} lines, ${byteCount} bytes`);
    }
    callback();
  }
}

let file = fs.createReadStream('test.xz');
let decompressor = lzma.createDecompressor();
let decompress = file.pipe(decompressor);
let lines = decompress.pipe(split(/\r?\n/));
lines.on('data', line => {
  byteCount += line.length;
});

let writer = new TestWriter();
writer.on('finish', () => {
  console.log("Finish");
  process.exit(0);
});
lines.pipe(writer);
```

**Comment by addaleax** [comment]
Thanks, I’m looking into this!

**Comment by addaleax** [comment]
Sorry to tell you, but I don’t think this is (much of) an issue with this module, but rather with the `split` module.
In your test file, around the byte mark you named, are some extremely long lines (up to 33 MB). Unfortunately, `split` has (due to its generic approach) a rather simplistic way of splitting at delimiters: It basically buffers up all data from the input stream until `string.split(regex)` returns more than one result.
Now, when the decompressor writes the blocks making up the long lines to the `split()` stream, each time a block of data is appended to `split()`’s internal buffer and the regex is run over it, resulting in O(n²) complexity and, thereby, in the extremely long delays (Your test script takes about 15 minutes on my machine).

I found at least two solutions for this:
* One: Increase the size of the data blocks. This is not really a fix or anything (and may even drive up memory consumption in many cases), but it brought the test script’s timing into the same order of magnitude as `unxz < test.xz | wc -l`. I’ve just released `lzma-native@0.5.2`, which introduces a `bufsize` option for streams with a default value of 64 KB. You can test for yourself by using `lzma.createDecompressor({bufsize: …})`. I’ve found a value of a few megabytes to be sufficient for speeding this particular script up a lot, definitely into the acceptable range.
* Two: Since you are only checking for newlines, the [`char-split`](https://www.npmjs.com/package/char-split) module might be just what you want. It splits a stream on a single character (default `\n`), which allows it to reduce the complexity of searching for the delimiter to O(n). Using `import split from 'char-split';` and `let lines = decompress.pipe(split());`, your test script runs in about 15 seconds, which is *very* close the native solution of `unxz` + `wc`. If it is important to you that you also can accept windows newlines, I’d suggest you just strip a possible trailing `\r` character manually of each line after splitting.

Thank you for your detailed bug report! If you think that I missed something (which is perfectly possible) or have any further questions, feel free to re-open this issue. :)

**Comment by atombender** [comment]
Awesome response, thank you! I had no idea my file contained lines of that length.

I appreciate the buffer size addition. But I agree that a simpler splitting stream is the way to go — though I can't get `char-split` to work. I'm not very familiar with pre-Streams 2.0 streams: When I pipe anything to it, it gets an object (a buffer, possibly?) that's not a string, and emits:

```
TypeError: Object [... bunch of lines in one chunk ...] has no method 'indexOf'
    at Stream.<anonymous> (./node_modules/char-split/index.js:14:36)
    at Stream.stream.write (./node_modules/char-split/node_modules/through/index.js:26:11)
    at [object Object].ondata (./node_modules/lzma-native/node_modules/readable-stream/lib/_stream_readable.js:583:20)
    at [object Object].emit (events.js:95:17)
    at readableAddChunk (./node_modules/lzma-native/node_modules/readable-stream/lib/_stream_readable.js:201:16)
    at [object Object].Readable.push (./node_modules/lzma-native/node_modules/readable-stream/lib/_stream_readable.js:165:10)
    at [object Object].Transform.push (./node_modules/lzma-native/node_modules/readable-stream/lib/_stream_transform.js:133:32)
    at ./node_modules/lzma-native/index.js:166:16
    at process._tickCallback (node.js:419:13)
```

My test case:

```
fs.createReadStream("test.xz", 'binary')
  .pipe(lzma.createDecompressor())
  .pipe(split())
  .pipe(fs.createWriteStream('/dev/null'));
```

Perhaps you have a better idea of what the cause is?

**Comment by addaleax** [comment]
Hm, the `[... bunch of lines in one chunk ...]` is kinda the interesting part here; I think it *should* be something like `<Buffer 70 f2 5a 02 00 00 00 00 70 f2 …>`… right? Are you using some node version up to 0.12 (`node -v`)? `Buffer` objects have `.indexOf()` only since after 0.12, so that might be the problem. If so, [buffer-indexof-polyfill](https://npmjs.org/package/buffer-indexof-polyfill) seems to be a solution for this.

**Comment by atombender** [comment]
It's literally just a fragment of the input, and `typeof` says `object`. Maybe it's a buffer. This is Node 0.10.33, sounds like the problem might be that. I'll try the polyfill, thanks!

**Comment by addaleax** [comment]
Okay, that’s something I have never seen then :D Let me know if it works!

**Comment by atombender** [comment]
Must be a buffer, because the polyfill worked. Thanks again, that saved me a bunch of googling and trial/error.

**Comment by addaleax** [comment]
Great! :)
