### ISSUE TITLE
Cannot node-gyp/nw-gyp because of nan breaking change.

### ISSUE THREAD

**Issue by YLivay** [addaleax/lzma-native#35]
Hey!

nodejs/nan introduced a breaking change in a non major version release, and since lzma native doesn't pin the exact versions building from source fails.

More info on https://github.com/nodejs/nan/blob/master/CHANGELOG.md
I see there are already issues opened about it on nan, but thought i'd report here too to suggest pinning exact versions in the future :)

**Comment by addaleax** [comment]
Hey, thanks for letting me know. Does this work if you use the latest version of Nan? If so, I’ll just bump the version for it. :)

**Comment by YLivay** [comment]
I've opened an issue in nan for this, they suspect it might be an issue with nwjs: https://github.com/nodejs/nan/issues/670

Using an older version *should* work. I'll try it out pinning v1.5.2 to nan 2.5.1 and see how it goes!

**Comment by YLivay** [comment]
Pinning the version does seem to work - the linux build went through :)

**Comment by YLivay** [comment]
Appveyor seems to have issues installing lzma native from our fork where we pin the version. Is there a chance to get a version out that pins nan to 2.5.1? That's the latest version that doesn't break.

**Comment by addaleax** [comment]
@YLivay done! But just so you know, I’ll warn you if I might have to bump nan to a higher version, but really this is a nw.js problem as explained in the nan issue :/

**Comment by mkrufky** [comment]
@YLivay We knew nan 2.5.1 would work for you, but as I explained in the nan issue, I think that nan 2.6.1 might also work, since it's before a patch that silenced some build warnings.  If you can actually test your setup with nan 2.6.1 (2.6.2 is the latest, i know) and it works, then we can fix it nan-side at the cost of a build warning for regular node.js users.  (I don't know if such a patch would get accepted to nan, but I'd at least like to know if it would fix things for you)

**Comment by addaleax** [comment]
I think this has been resolved in nan (as a problem with nw)? I don’t think there’s much I can do here, but please ping me if there’s any more trouble.
